In [22]:
import pandas as pd
import numpy as np
from sklearn import preprocessing 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_extraction import FeatureHasher

In [63]:
dataset = pd.read_csv('BitcoinHeistData.csv',delimiter=',').dropna()
dataset.dataframeName='BitcoinHeistData.csv'
nRow, nCol = dataset.shape
print(f'there are {nRow} entries and {nCol} features.')

there are 1079963 entries and 10 features.


In [64]:
dataset

address  year  day  length    weight  \
0         111K8kZAEnJg245r2cM6y9zgJGHZtJPy6  2017   11      18  0.008333   
1        1123pJv8jzeFQaCV4w644pzQJzVWay2zcA  2016  132      44  0.000244   
2        112536im7hy6wtKbpH1qYDWtTyMRAcA2p7  2016  246       0  1.000000   
3        1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7  2016  322      72  0.003906   
4        1129TSjKtx65E35GiUo4AYVeyo48twbrGX  2016  238     144  0.072848   
...                                     ...   ...  ...     ...       ...   
1079958   1sfQz7NsNqwrRxSt55f969Gb8Ps9797T4  2013  319       6  0.250000   
1079959  15d2gorPZK24StQgME1M3rMgTNgtfjrz42  2013  319       4  0.125000   
1079960  1PSTya5xeaCMjMpb9PAmqUMo1GM8i7uFYh  2013  319       0  0.500000   
1079961  19VWG5Meocycq2Uauyai63JRZbdmxPy7Xn  2013  319       0  0.500000   
1079962  1LoJMA2wj6DqFZwErBGX7z2vTsdyMg1EWb  2013  319      10  0.015625   

         count  looped  neighbors        income            label  
0          1.0     0.0        2.0  1.000500e+08  princetonCerber  
1          1.0     0.0        1.0  1.000000e+08   princetonLocky  
2          1.0     0.0        2.0  2.000000e+08  princetonCerber  
3          1.0     0.0        2.0  7.120000e+07  princetonCerber  
4        456.0     0.0        1.0  2.000000e+08   princetonLocky  
...        ...     ...        ...           ...              ...  
1079958    1.0     0.0        1.0  1.500000e+08            white  
1079959    1.0     0.0        2.0  4.111800e+09            white  
1079960    1.0     0.0        1.0  1.245662e+08            white  
1079961    1.0     0.0        1.0  4.000000e+07            white  
1079962    1.0     0.0        2.0  1.137718e+09            white  

[1079963 rows x 10 columns]

In [65]:
dataset.columns

Index(['address', 'year', 'day', 'length', 'weight', 'count', 'looped',
       'neighbors', 'income', 'label'],
      dtype='object')

In [66]:
label_encoder = preprocessing.LabelEncoder()
dataset['address_enc'] = pd.util.hash_pandas_object(dataset['address'])
dataset['label_enc'] = label_encoder.fit_transform(dataset['label'])


print(dataset.head(3))

                               address  year  day  length        weight  \
0    111K8kZAEnJg245r2cM6y9zgJGHZtJPy6  2017   11      18  8.333333e-03   
1   1123pJv8jzeFQaCV4w644pzQJzVWay2zcA  2016  132      44  2.441406e-04   
2   112536im7hy6wtKbpH1qYDWtTyMRAcA2p7  2016  246       0  1.000000e+00   
3   1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7  2016  322      72  3.906250e-03   
4   1129TSjKtx65E35GiUo4AYVeyo48twbrGX  2016  238     144  7.284841e-02   
5   112AmFATxzhuSpvtz1hfpa3Zrw3BG276pc  2016   96     144  8.461400e-02   
6   112E91jxS2qrQY1z78LPWUWrLVFGqbYPQ1  2016  225     142  2.088519e-03   
7   112eFykaD53KEkKeYW9KW8eWebZYSbt2f5  2016  324      78  3.906250e-03   
8   112FTiRdJjMrNgEtd4fvdoq3TC33Ah5Dep  2016  298     144  2.302828e+00   
9   112GocBgFSnaote6krx828qaockFraD8mp  2016   62     112  3.725290e-09   
10  112gXL4AeJ62DX3htuLhBc3MtY5U6X5J28  2013  317       4  7.142857e-03   
11  112nEBUadWiMxzUUASNZpQ9AvePtrJVuca  2016  247       0  1.000000e+00   
12  112Ns49UobQn1cX1G1axs

In [67]:
X = dataset.drop(['address', 'label', 'label_enc'], axis=1)
y = dataset['label_enc']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [68]:
np.unique(y, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]),
 array([     11,       1,       7,    2419,    9315,      55,     251,
            354,       6,       9,      32,      55,      34,       4,
            483,      13,       1,      62,       7,      28,       1,
              7,       8,   12390,       2,      10,    9223,    6625,
        1038550], dtype=int64))

In [69]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1079963 entries, 0 to 1079962
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype  
---  ------       --------------    -----  
 0   year         1079963 non-null  int64  
 1   day          1079963 non-null  int64  
 2   length       1079963 non-null  int64  
 3   weight       1079963 non-null  float64
 4   count        1079963 non-null  float64
 5   looped       1079963 non-null  float64
 6   neighbors    1079963 non-null  float64
 7   income       1079963 non-null  float64
 8   address_enc  1079963 non-null  uint64 
dtypes: float64(5), int64(3), uint64(1)
memory usage: 82.4 MB


In [70]:
gb=GradientBoostingClassifier(random_state=0)
gb=gb.fit(X_train,y_train)
gb.score(X_test,y_test)

0.9745361882433118

In [84]:
X_test.iloc[1]

year           2.012000e+03
day            9.500000e+01
length         6.000000e+00
weight         6.250000e-02
count          1.000000e+00
looped         0.000000e+00
neighbors      2.000000e+00
income         5.650895e+07
address_enc    1.540581e+18
Name: 490766, dtype: float64

In [91]:
gb.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'deviance',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': 0,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [88]:
gb.decision_function(X_test.iloc[0:1])

array([[-2.09495393e+01, -2.32476129e+01, -2.18613208e+01,
        -1.57299362e+01,  1.17940998e+03, -3.95804337e+58,
        -1.78385484e+01, -1.76756670e+01, -2.16381784e+01,
        -2.11380114e+01, -2.01121363e+01, -1.55842838e+01,
        -1.99517968e+01, -2.25544665e+01, -1.17461981e+01,
        -1.11105308e+01, -2.32476129e+01, -1.93975021e+01,
        -2.13017076e+01, -2.01565876e+01, -2.16381781e+01,
        -2.11543244e+01, -8.28965978e+00, -2.32476129e+01,
        -2.11681770e+01, -1.44101213e+01, -1.47364154e+01,
         1.07718389e+00]])

In [73]:
gb.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'deviance',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': 0,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}